routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('task', 'TaskController');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
    protected $fillable = [
                'title',
            'task',
            'time',
            'date'
        ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $tasks = Task::all();//assign list all list to tasks

        return view('task.index', compact('tasks'));//defines view and passing tasks
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //  
       return view('task.create');

   }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
      $request->validate([
        'title'=>'required|string',
        'task'=> 'required|string',
        'time' => 'required|string',
        'date' => 'required|string'
    ]); //validate the form value

      $task = new Task([
        'title' => $request->get('title'),
        'task'=> $request->get('task'),
        'time'=> $request->get('time'),
        'date'=> $request->get('date'),
    ]);//assign form values to object
      $task->save(); //saving object to database
      return redirect('/task')->with('success', 'task has been added');
  }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $task = Task::find($id);

        return view('task.details', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $task = Task::find($id);

        return view('task.details', compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        //
              $request->validate([
        'title'=>'required|string',
        'task'=> 'required|string',
        'time' => 'required|string',
        'date' => 'required|string'
      ]);

      $task = Task::find($id);
      $task->title = $request->get('title');
      $task->task = $request->get('task');
      $task->time = $request->get('time');
      $task->date = $request->get('date');
      $task->save();

      return redirect('/task')->with('success', 'Task has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
             $task = Tk::find($id);
     $task->delete();

     return redirect('/task')->with('success', 'Task has been deleted Successfully');
    }
}

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Laravel Example Tutorial To Do Task</title>
	<link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" type="text/css" href="{{ asset('css/timepicki.css') }}">

</head>
<body>
	<div class="container">
		@yield('content')
	</div>
	<script src="{{ asset('js/app.js') }}" type="text/js"></script>
	<!-- <script src="{{ asset('js/jquery.js') }}"></script> -->
	<script
	src="https://code.jquery.com/jquery-3.4.1.min.js"
	integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
	crossorigin="anonymous"></script>
	<script src="{{ asset('js/timepicki.js') }}"></script>
	<!-- <script src="{{ asset('js/custom.js') }}" type="text/js"></script> -->
	<script>
		$(document).ready(function(){
			$(".timepicker").timepicki();
		});
	</script>
</body>
</html>

resources/views/task/create.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Task
  </div>
  <div cla ss="card-body">
    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div><br />
    @endif
    <form method="post" action="{{ route('task.store') }}">
      <div class="form-group">
        @csrf
        <label for="name">Title:</label>
        <input type="text" class="form-control" name="title"/>
      </div>
      <div class="form-group">
        <label for="price">task:</label>
        <textarea class="form-control" name="task"></textarea>
      </div>
      <div class="form-group">
        <label for="input_starttime">Time</label> 
        <input placeholder="Selected time" name="time" type="text" id="input_starttime" class="form-control timepicker">
      </div>
      <div class="form-group">
        <label for="input_date">Date</label> 
        <input placeholder="Selected date" name="date" type="date" id="input_date" class="form-control datepicker">
      </div>
      <button type="submit" class="btn btn-primary">Add</button>
    </form>
  </div>
</div>
@endsection

resources/views/task/details.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Task details
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('task.update', $task->id) }}">
        @method('PATCH')
        @csrf
      <div class="form-group">
        @csrf
        <label for="name">Title:</label>
        <input type="text" class="form-control" name="title" value="{{$task->time}}" />
      </div>
      <div class="form-group">
        <label for="price">task:</label>
        <textarea class="form-control" name="task">{{$task->task}}</textarea>
      </div>
      <div class="form-group">
        <label for="input_starttime">Time</label> 
        <input placeholder="Selected time" name="time" type="text" id="input_starttime" class="form-control timepicker" value="{{$task->time}}" >
      </div>
      <div class="form-group">
        <label for="input_date">Date</label> 
        <input placeholder="Selected date" name="date" type="date" id="input_date" class="form-control datepicker" value="{{$task->date}}" >
      </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/task/index.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Title</td>
          <td>Task/td>
          <td>Time</td>
          <td>Date</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($tasks as $task)
        <tr>
            <td>{{$task->id}}</td>
            <td>{{$task->title}}</td>
            <td>{{$task->task}}</td>
            <td>{{$task->time}}</td>
            <td>{{$task->date}}</td>
            <td><a href="{{ route('task.edit',$task->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('task.destroy', $task->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection